[Variables]
Latitude=29.704813
Longitude=72.560036
LocalityLanguage=en
ReverseGeo_Debug_Path=ReverseGeo.json
; Options  0,1,2
; 0: Does not log DEBUG messages from WebParser.
; 1: Logs DEBUG message to the log. Rainmeter must also be in Debug mode.
; 2: Saves the downloaded webpage to a file.
ReverseGeoDebug=0
; The rate in milliseconds determining how often the webpage is 
; downloaded. This is relative to the config's main Update rate 
; and any UpdateDivider on the measure. 
; So the formula would be 
; Update X UpdateDivider X UpdateRate = "how often the measure connects to the site".
ReverseGeo_Update_Rate=3600
